name: Deploy to WordPress.org
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get tag name
      id: get_tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Install SVN
      run: |
        sudo apt-get update
        sudo apt-get install subversion -y

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: wp-cli

    - name: Build and prepare plugin
      run: |
        # Create SVN-compatible structure
        mkdir -p svn-repo/trunk
        mkdir -p svn-repo/assets
        mkdir -p svn-repo/tags/${{ steps.get_tag.outputs.VERSION }}

        # Copy plugin files to trunk
        cp -R trunk/* svn-repo/trunk/
        cp -R assets/* svn-repo/assets/

        # Create version-specific tag
        cp -R trunk/* svn-repo/tags/${{ steps.get_tag.outputs.VERSION }}/

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_PASSWORD }}
        SLUG: jwt-cookie-bridge
        VERSION: ${{ steps.get_tag.outputs.VERSION }}
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}