name: Deploy Plugin
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Zip Plugin
        run: |
          zip -r christendom-sso.zip . -x "*.git*" -x "*.github*"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: christendom-sso.zip