name: Deploy to WordPress.org
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  tag-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag name
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release Artifact
        run: |
          mkdir -p release/jwt-cookie-bridge
          cp -r trunk/* release/jwt-cookie-bridge/
          cp -r assets release/jwt-cookie-bridge/assets
          cd release
          zip -r jwt-cookie-bridge-${{ steps.get_tag.outputs.VERSION }}.zip jwt-cookie-bridge/
          cd ..
          mv release/jwt-cookie-bridge-${{ steps.get_tag.outputs.VERSION }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jwt-cookie-bridge-${{ steps.get_tag.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wordpress-deploy:
    name: WordPress.org Deploy
    runs-on: ubuntu-latest
    needs: tag-release
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag name
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_PASSWORD }}
          SLUG: jwt-cookie-bridge
          VERSION: ${{ steps.get_tag.outputs.VERSION }}