name: Deploy Plugin
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
              
      - name: Create Plugin Directory Structure
        run: |
          mkdir -p build/jwt-cookie-bridge
          cp -r src build/jwt-cookie-bridge/
          cp -r assets build/jwt-cookie-bridge/
          cp jwt-cookie-bridge.php build/jwt-cookie-bridge/
          cp readme.txt build/jwt-cookie-bridge/
          cp README.md build/jwt-cookie-bridge/
              
      - name: Zip Plugin
        run: |
          cd build && zip -r ../jwt-cookie-bridge-${{ env.VERSION }}.zip jwt-cookie-bridge/
              
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jwt-cookie-bridge-${{ env.VERSION }}.zip